# Generated by Django 3.0.8 on 2020-07-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200704_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='writer',
        ),
    ]
